### ISSUE TITLE
Install breaks due to package name conflict

### ISSUE THREAD

**Issue by lkarlslund** [badsectorlabs/sccm-http-looter#1]
Great work, thanks for the effort in creating this. I look forward to testing it.

Using this command line to install your tool:

```
go install github.com/badsectorlabs/sccm-http-looter@latest
``` 

I get this error message:

```
go: downloading github.com/badsectorlabs/sccm-http-looter v0.0.0-20240811191751-b595c1fce35d
go: github.com/badsectorlabs/sccm-http-looter@latest: version constraints conflict:
	github.com/badsectorlabs/sccm-http-looter@v0.0.0-20240811191751-b595c1fce35d: parsing go.mod:
	module declares its path as: sccmlooter
	        but was required as: github.com/badsectorlabs/sccm-http-looter
```

The error message is self explanatory, and I suggest you rename your package in order to fix this.

If you want to do automated builds, you can take a look at how I do this using Github actions on some of my stuff (eg. ldapnomnom, fastsync or others) - just a suggestion, it will make adoption of your tool way easier for users.

**Comment by kernel-sanders** [comment]
Sorry about that!

Package name has been fixed and goreleaser has been added to the project. Release binaries are now available.
